version: "3"
services:
    app:
        build: 
            context: .
            args:
                NodeJsVer: ${nodejs_version} 
                ClaspVer: ${clasp_version}
                TypeScriptVer: ${typescript_version}
        environment:
            TZ: "Asia/Tokyo"
        volumes:
            - "./repository:/var/repository"
            - "./root:/root"
        stdin_open: true
        tty: true